# Generated by Django 5.1.6 on 2025-02-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('publicUser', 'User'), ('administrator', 'Administrator'), ('worker', 'Supervisor')], default='user', max_length=20),
        ),
    ]
