# Generated by Django 5.1.6 on 2025-02-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('publicUser', 'User'), ('administrator', 'Administrator'), ('worker', 'Worker')], default='publicUser', max_length=20),
        ),
    ]
