# Generated by Django 5.1.6 on 2025-02-11 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_wastepickup_wastereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'administrator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
